---
title: "MBL Example"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r setup 1, include=FALSE}


library(tidyverse)
library(rio)
library(here)
library(gghighlight)
library(forcats)
library(ggrepel)
library(gt)
library(knitr)
library(kableExtra)
library(reactable)
library(plotly)
library(SCVA)
library(patchwork)
library(colorblindr)
library(scan)



theme_set(theme_minimal(15) +
            theme(legend.position = "bottom",
                  panel.grid.major.x = element_line(color = "gray60"),
                  panel.grid.minor.x = element_blank(),
                  panel.grid.major.y = element_blank())
          )

participant_1 <- import(here("data", "participant_1_data.xlsx"),
               setclass = "tbl_df") 

participant_2 <- import(here("data", "participant_2_data.xlsx"),
               setclass = "tbl_df") 

participant_3 <- import(here("data", "participant_3_data.xlsx"),
               setclass = "tbl_df") 
 


```


```{r, include=FALSE}
head(participant_1)

p_1_plot <- ggplot() +
  geom_line(data = participant_1, aes(x = session, y = bl)) +
  geom_point(data = participant_1, aes(x = session, y = bl), size = 2) +
  geom_line(data = participant_1, aes(x = session, y = tx)) +
  geom_point(data = participant_1, aes(x = session, y = tx), size = 2) +
  scale_x_continuous(limits = c(0, 13),
                     breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13)) +
  scale_y_continuous(limits = c(0, 60),
                     breaks = c(0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60)) +
  theme_classic() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank()) +
  labs(x = "Session",
       y = "Participant 1 Axis") 

p_1_plot

p_2_plot <- ggplot() +
  geom_line(data = participant_2, aes(x = session, y = bl)) +
  geom_point(data = participant_2, aes(x = session, y = bl), size = 2) +
  geom_line(data = participant_2, aes(x = session, y = tx)) +
  geom_point(data = participant_2, aes(x = session, y = tx), size = 2) +
  scale_x_continuous(limits = c(0, 13),
                     breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13)) +
  scale_y_continuous(limits = c(0, 60),
                     breaks = c(0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60)) +
  theme_classic() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank()) +
  labs(x = "Session",
       y = "Participant 2 Axis") 

p_2_plot

p_3_plot <- ggplot() +
  geom_line(data = participant_3, aes(x = session, y = bl)) +
  geom_point(data = participant_3, aes(x = session, y = bl), size = 2) +
  geom_line(data = participant_3, aes(x = session, y = tx)) +
  geom_point(data = participant_3, aes(x = session, y = tx), size = 2) +
  scale_x_continuous(limits = c(0, 13),
                     breaks = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13)) +
  scale_y_continuous(limits = c(0, 60),
                     breaks = c(0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60)) +
  theme_classic() +
  labs(x = "Session",
       y = "Participant 1 Axis") 

p_3_plot

all_plots <- p_1_plot / p_2_plot / p_3_plot


all_plots
```

```{r, include=TRUE, fig.height=8, fig.width=10}
all_plots
```

## SCAN Demonstration {.tabset .tabset-fade .tabset-pills}

```{r, include=FALSE}
case_1 <- scdf(
  values = c(A = 10, 10, 10, B = 20, 20, 20, 23, 24, 25, 25, 25, 30, 33), 
  name = "KAHI"
)

case_2 <- scdf(
  values = c(A = 10, 10, 10, 13, 13, 15, B = 23, 24, 30, 30, 36, 30, 40), 
  name = "GASY"
)

case_3 <- scdf(
  values = c(A = 10, 10, 10, 13, 13, 15, 18, 18, B = 30, 30, 42, 42, 50), 
  name = "GOZO"
)

all_mbl_data <- c(case_1, case_2, case_3)
```


```{r, include=FALSE}
marks <- list(
  positions = list( c(8, 9), c(17, 19), c(7, 18) ), 
  col = 'red', cex = 2.5, pch = 1
)
plot(exampleAB, marks = marks, style = "sienna")

head(exampleAB)
exampleAB

plot(exampleAB)

plot(all_mbl_data) 
```

### Version 1

```{r, include=TRUE, fig.height=8, fig.width=10}
plot(all_mbl_data)
```

```{r, include=FALSE}

plot_style = style_plotSC(style = "chart",
                          fill = "grey50",
                          grid = "lightblue",
                          pch = 16)

plot_v2 <- plot(
  all_mbl_data,
  xlab = "session",
  ylab = "Participant Measurement",
  phase.names = c("Baseline", "Treatment"),
  ylim = c(0, 50),
  style = plot_style)

```

### Version 2

```{r, include=TRUE, fig.height=8, fig.width=10}
plot(
  all_mbl_data,
  xlab = "session",
  ylab = "Participant Measurement",
  phase.names = c("Baseline", "Treatment"),
  ylim = c(0, 50),
  style = plot_style)
```